name: Kwiki-GDGraphGenerator
version: 0.04
abstract: put pretty graphs into your Kwiki pages
author: Ian Langworth <ian@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.32
  GD::Graph: 1.40
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.39
